### numpy 基础

In [9]:
import numpy as np

1.查看 numpy 版本

In [4]:
np.__version__

'1.17.2'

## numpy.array 的使用

1.numpy 数组的初始化

In [ ]:
# 使用 for 循环声明
nparry=np.array([i for i in range(10)])
nparry

In [26]:
# 赋值声明
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

2.查看 array 数据的存储类型
<br>默认是 int 类型

In [6]:
nparry.dtype

dtype('int64')

In [11]:
# 声明一个 float 类型的矩阵
nparry2=np.array([1,2.3,3.14])
nparry2.dtype

dtype('float64')

### 创建特殊 array

In [13]:
#1.创建一个为 int 类型的list,全为数据0，如果第二个参数不写默认为 float
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#2.创建全为数据1的数据
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
#3.创建一个 二维数组.其中 shape和 dtype 可以不写
np.zeros(shape=(3,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
#4.创建一个所有值都是某一个数的矩阵
np.full(shape=(3,5),fill_value=111)

array([[111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111]])

## linspace
创建等差数列

In [ ]:
#1.创建一个列表 （起始，终止（包含），将这个范围内的数组成一个长度为多少的等差）
np.linspace(0,20,11)

### random
创建随机矩阵

In [5]:
# 1.创建一个随机数 (前闭，后开)
np.random.randint(0,10)

array([7, 1, 5, 1, 3, 6, 6, 5, 8, 5])

In [29]:
#2.创建一个随机数组(二维),类型为 int 
np.random.randint(0,10,size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [27]:
#3.随机种子，随机序列并不是真正意义上的随机
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [12]:
#4.生成随机浮点数
np.random.random(size=(3,5))

array([[0.28116849, 0.46284169, 0.23340091, 0.76706421, 0.81995656],
       [0.39747625, 0.31644109, 0.15551206, 0.73460987, 0.73159555],
       [0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197]])

In [13]:
#5.生成一个符合概率论某分布的随机数(均值，标准差)
#生成一个符合正态分布的随机数组
np.random.normal(0,1,size=(3,5))

array([[ 0.61360982, -0.21747638,  0.22196962, -1.86735182, -0.25584759],
       [-1.76438083, -0.94249688, -1.58045861,  0.90472662, -0.82628327],
       [ 0.82101369,  0.36712592,  1.65399586,  0.13946473, -1.21715355]])

### 查询框架文档的两种方法

In [17]:
#1.新添网页添加文档
np.random.normal?

In [19]:
#2.在下方添加文档
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution. Must be
        non-negative.
    size : int or 