### numpy.array  的 查找，xiu

In [2]:
import numpy as np

In [3]:
# 生成 0～10 之间的数组
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1. Reshape
更改数组的维度.（横向：样本个数。纵向：属性个数）

In [4]:
# 1.将一维数组改为二维数组
X=np.arange(15).reshape((3,5))
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
#2.当不知道列表元素个数的时候，根据行/列的需求自动将列表划分
x.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [22]:
#这个方法不会改变 x 自身,输出x依旧为一维数组
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#只有在赋予新的列表的时候这个值才会改变
A=x.reshape(2,-1)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 2. 数组的基本属性

In [6]:
#1.维度计算
x.ndim

1

In [5]:
#2.数组的类型
X.shape

(3, 5)

In [8]:
#3.元素个数
X.size

15

### 3. numpy.array的数据访问
对于 array 的操作如同 python 的列表语法

In [9]:
#1.对于一维数组访问如同 python 基本语法
x[2]

2

In [10]:
#2.对于二维数组，一般不用两个方括号进行数据的提取 X[][]
X[2,2]

12

### 3.1切片

In [6]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
#1.对于一个数组进行切片（一维数组的前两行，再将前两行取前三列）,后面的数取不到
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [12]:
#2.为什么不用两个 [][],因为这样会将X整体看为多行的一维数组
#取值为 (X[])[]
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
#3.对于一列进行数据提取
X[:,0]

array([ 0,  5, 10])

### 4.矩阵的赋值与修改
如果将 X 直接赋值给另一个数组，另一个数组改变也会导致 X 的改变

In [14]:
#1.将矩阵 X 赋值给 subX
subX=X
subX

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
#2.更改 subX 的值，X的值也会相应更改
subX[0,0]=100
subX

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [16]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [17]:
#3.仅将 subX 进行 赋值，subX更改时X不更改copy() 
subX2=X.copy()
subX2

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [18]:
subX2[0,0]=300
subX2

array([[300,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [19]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

### 5.合并与分割操作

### 5.1 合并操作

In [26]:
 # 1.一维数组的合并，这样的合并可以看做两个样本的合并
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.array([666,666,666])
#将元素拼接
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [28]:
#二维数组的合并,array 中只能放一个参数，所以在一个中括号之后还要再加一个中括号
A=np.array([[1,2,3],
           [4,5,6]])
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [29]:
#2.一个样本中两个属性的和并.axis 属性是轴，默认 为0
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [30]:
# 3.将两个不一样维度的矩阵进行拼接(方法一)
#一般情况下将两个不一样的维度进行拼接一定会出错
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [31]:
#将两个不同维度的矩阵进行拼接（方法二）
#这个方法有更好的容错性，且这个方法是在垂直的方向上
np.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [32]:
#在水平方向上将数组进行拼接,相当于某个样本的属性拼接
B=np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [33]:
#属性合并
np.hstack([B,B])

array([[100, 100, 100, 100],
       [100, 100, 100, 100]])

### 5.2 分割操作

In [39]:
x=np.array([2,4,6,8,10,12,14,16,18,20])
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
#[] 中指第几个为一组，是包含的
x1,x2,x3 = np.split(x,[3,7])

In [10]:
x1

array([0, 1, 2])

In [42]:
x2

array([ 8, 10, 12, 14])

In [43]:
x3

array([16, 18, 20])

In [49]:
x4,x5 = np.split(x,[2])
x5

array([ 6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
x4

array([2, 4])

In [54]:
#2.对 二维数组进行水平和垂直的分割
A = x.reshape((5,2))
A

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [56]:
upper,lower = np.vsplit(A,[2])
upper

array([[2, 4],
       [6, 8]])

In [57]:
lower

array([[10, 12],
       [14, 16],
       [18, 20]])

In [59]:
#3.实战 ,下面生成的为一个数据集
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
# 每一维是一个样本，每个样本中有不同的属性
#取最后一列的结果值，,2 就是倒数两列
x,y=np.hsplit(data,[-1])
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [61]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [62]:
# 这时的 y 是多维列表不是向量，或者说不是一维的
#将其变为向量
y[:,0]

array([ 3,  7, 11, 15])