### numpy.array 的基本运算

### 乘法操作

In [2]:
import numpy as np

In [3]:
#1.numpy 中的乘法操作
a = np.array([0,1,2])
a*2

array([0, 2, 4])

In [4]:
#2.在普通 python 语言中的 *2 效果.将数组进行拼接
L = [i for i in range(3)]
L*2

[0, 1, 2, 0, 1, 2]

In [5]:
# 普通python 语言置为两倍，但是时间效率非常低
l=[]
for e in L:
    l.append(2*e)
l

[0, 2, 4]

### 2.基本运算
因为 numpy 将array 看做一个矩阵，所以隐含的 Universal Funtions 这个功能可以直接进行运算

In [6]:
X = np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [10]:
# 浮点数的除法
1/X

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [11]:
#整数的除法
X//2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [13]:
# 求绝对值
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
# 求正弦函数
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

### 3.矩阵矩阵之间的运算
在进行运算的过程中要保证两个矩阵之间是可以进行运算的

In [16]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [18]:
B = np.arange(4,8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

In [20]:
# 1.两个矩阵之间的加法运算
A+B

array([[ 4,  6],
       [ 8, 10]])

In [21]:
# 2. 矩阵的乘法
#矩阵的乘法是对应元素做相应的运算
A  * B

array([[ 0,  5],
       [12, 21]])

In [22]:
# 3.真正的矩阵乘法
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [23]:
# 4.矩阵的转置
A.T

array([[0, 2],
       [1, 3]])

### 向量和矩阵的运算

In [24]:
v = np.array([1,2])
v

array([1, 2])

In [28]:
#1.加法，就是向量和矩阵中的每一行做加法

v+A

array([[1, 3],
       [3, 5]])

In [29]:
#但是维度不一样是不可以进行相乘的，所以可以手动将 v 的维度进行变化
np.vstack([v]*A.shape[0])

array([[1, 2],
       [1, 2]])

In [30]:
np.vstack([v]*A.shape[0])+A

array([[1, 3],
       [3, 5]])

In [31]:
# 2. 矩阵的乘法
v.dot(A)

array([4, 7])

In [32]:
# 向量和矩阵相乘，如果不符合规定，程序会自动将向量进行转置
A.dot(v)

array([2, 8])

### 矩阵的逆

In [34]:
A

array([[0, 1],
       [2, 3]])

In [36]:
#矩阵求逆，但是不是所有矩阵都有逆矩阵
invA = np.linalg.inv(A)
invA 

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [37]:
# A invA =E 逆矩阵的证明 
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [40]:
#2.非方阵的逆矩阵（伪逆矩阵）
X = np.arange(16).reshape(2,8)
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [43]:
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [44]:
# 伪逆矩阵 的证明就是 矩阵*伪逆矩阵=E(非对角线的结果近似于0)
X.dot(pinvX)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])