### 1.聚合操作

In [27]:
import numpy as np
L = np.random.random(100)
L

array([0.35938019, 0.56705784, 0.38733912, 0.66012711, 0.74810803,
       0.08999572, 0.47644837, 0.22204071, 0.72612778, 0.74907655,
       0.58706124, 0.77728253, 0.77858846, 0.45435214, 0.90031379,
       0.1993901 , 0.38167708, 0.31628356, 0.19268336, 0.84495094,
       0.04029661, 0.968459  , 0.80278556, 0.28868632, 0.26861184,
       0.35789595, 0.80354061, 0.54087299, 0.020366  , 0.24760215,
       0.10851367, 0.02302548, 0.65432287, 0.3462665 , 0.5212793 ,
       0.28409364, 0.14597225, 0.1067902 , 0.84661628, 0.64450868,
       0.3857967 , 0.50147734, 0.82368271, 0.35004001, 0.78211062,
       0.87285454, 0.27546079, 0.85624158, 0.65406441, 0.46467212,
       0.32639712, 0.21543474, 0.49706914, 0.60493753, 0.25133727,
       0.77828149, 0.90327088, 0.05485408, 0.21230335, 0.27321936,
       0.45862027, 0.61222421, 0.80190792, 0.28622816, 0.12664262,
       0.95177738, 0.3766733 , 0.63105297, 0.75181382, 0.52832553,
       0.83928511, 0.9011959 , 0.96552508, 0.73430454, 0.37563

In [28]:
#1.计算矩阵中数值的和
np.sum(L)

49.84629429433223

In [29]:
#2.求一组数的最小值/最小值的两种方法
#很多聚合方法都可以用面向对象 . 的方法进行操作，但是更常用第二个方法用的更多
#对象 . 的方法是会改变值的，但是用 np 的方法是不会改变值的
np.min(L)
L.min()

0.020366002750422663

In [30]:
#3.对于二维数组的聚合运算
X = np.arange(16).reshape(4,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
# 1.将二维数组所有数求和
np.sum(X)

120

In [32]:
#2.将矩阵转换成一个个的列向量组成为单位求和
#这时矩阵是一行
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [33]:
#2.将矩阵转换成一个个的行向量组成为单位求和
#这时矩阵是一列
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [34]:
#3.先将矩阵中每个数+1再求每个元素之间的相乘
np.prod(X+1)

20922789888000

In [35]:
#4.求平均值
np.mean(X)

7.5

In [36]:
#5.求中位数
np.median(X)

7.5

In [37]:
#4.百分数的使用，这个数组中 百分之 q 的值都比结果小
#X 数组中 50% 的数都比结果小
np.percentile(X,q=50)

7.5

In [40]:
# 用 for 循环分别求出 25%的水平，50%的水平,75%,100%d的水平
for percent in [0,25,50,75,100]:
    print(np.percentile(X,q=percent))

0.0
3.75
7.5
11.25
15.0


In [47]:
#定义一个符合正态分布的随机数
x = np.random.normal(0,1,size=10)
x

array([ 1.71500891,  0.09521813, -0.14494112,  0.9041468 , -0.01573423,
       -1.68164843,  1.71593035,  1.27273553,  0.42624609, -0.70885424])

In [48]:
#5.求方差（方差接近于 1）
np.var(x)

1.0585147650709512

In [50]:
#6.标准差(标准差接近于1)
np.std(x)

1.0288414674141741

### 2.索引操作

In [51]:
# 1.找到最小值/最大值
np.min(x)

-1.68164843227183

In [54]:
# 索引到最小值的下标
np.argmin(x)

5

In [55]:
# 从输出结果来看，下标为 5 的就是最小值
x[5]

-1.68164843227183

### 3.排序和使用索引

In [56]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
# 先对 x 进行乱序处理
np.random.shuffle(x)
x

array([15,  4,  6, 10, 14,  5,  1,  8,  2,  9,  0,  7,  3, 12, 13, 11])

In [73]:
# 1.对 x (一维)进行排序
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [69]:
#2.声明一个随机的二维数组，对其进行排序
X = np.random.randint(16,size=(4,4))
X

array([[ 7,  6,  5,  7],
       [ 3,  2, 12,  5],
       [12,  7, 10, 11],
       [14,  0,  0,  0]])

In [70]:
# 内部其实是将二维数组的每一行进行了排序，axis这里的默认值是1
np.sort(X)

array([[ 5,  6,  7,  7],
       [ 2,  3,  5, 12],
       [ 7, 10, 11, 12],
       [ 0,  0,  0, 14]])

In [74]:
#3.索引和排序相结合。显示的结果x[0]为 :数组中最小的元素的下标值
np.argsort(x)

array([10,  6,  8, 12,  1,  5,  2, 11,  7,  9,  3, 15, 13, 14,  4,  0])

In [75]:
# 4.模拟一趟快速排序，第二个参数是以哪个数为基准，左边是比他小的值，右边是比他大得值
np.partition(x,3)

array([ 0,  1,  2,  3,  4,  5,  8, 10,  6,  9,  7, 11, 14, 12, 13, 15])

In [77]:
# 在索引的情况下进行一次快排
np.argpartition(x,3)

array([10,  6,  8, 12,  1,  5,  7,  3,  2,  9, 11, 15,  4, 13, 14,  0])