### Fancy Indexing

In [2]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
#1.得到规定下标值的向量
ind =[3,5,8]
x[ind]

array([3, 5, 8])

In [4]:
# ind 是一个矩阵，最后会以 ind 定义的形式返回
ind = np.array([[0,2],
               [1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [4]:
#2.对二维数组进行操作，以点的形式传入索引
X = x.reshape(4,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
#这些点是相互对应的 [0][1],[1][2],[2][3]
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [6]:
# 3.通过切片的方式确定行，通过布尔值的方式确定列（非常重要）
# 得到下标 1,2 行的所有，列除了第二列，其他都有
col=[True,False,True,True]
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

In [21]:
# 4. [] 中的条件是 逻辑条件,显示满足这个逻辑条案件的所有数据
x[x %2 ==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [8]:
# 5.二维数组实现：取所有的样本下标3的特征值，进行取余判断
#行的判断：先将所有的行中的3位上的值进行取余3的判断
#列的操作：取满足条件行的一整行
X[X[:,3] % 3==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

### numpy.array 的比较
比较返回的都是布尔类型的结果

In [9]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
# 1.将列表的元素进行数值比较，得到布尔类型的结果
x <3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [11]:
# 2.算数运算符+逻辑运算符进行结合
x+3 > 5

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [12]:
# 3. 对 布尔类型的结果进行求和
np.sum(x>3)

12

In [13]:
#4.判断语句中有几个为 True 的 ，True ==1
np.count_nonzero(x<3)

3

In [14]:
 # 5.参数结果中只要有 True 就会返回 True
np.any(x==0)

True

In [15]:
# 6.参数结果中要所有的值都是 True 才会返回 True
np.all(x>=0)

True

In [16]:
# 7.用于二维数组，判断偶数的个数
np.sum(x %2 == 0)

8

In [17]:
# 8.看每一行有多少偶数
np.sum(X%2==0,axis=1)

array([2, 2, 2, 2])

In [18]:
# 9.& 位运算符。这里没有用 &&。 因为这里的x 不是布尔值
# 所以将每个元素看做一个位
np.sum((x > 3)& (x < 10))

6

In [19]:
# 10.或者的条件
np.sum((x%2==0)|(x>12))

10

In [20]:
# 11.非运算
np.sum(~(x==0))

15